name: actions

on:
    pull_request:
        branches: [ dev ]

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo Hello World

    snyk-scan:
        runs-on: ubuntu-latest
    
        steps:
            - name: Check out code
              uses: actions/checkout@v3
    
            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/maven@master
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                command: monitor
            
